import mongoose from "mongoose";

const ausmallFinanceFormSchema = new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    createdByRole:{
        type:String,
        enum:['valuer', 'site-engineer', 'technical-engineer', 'office-engineer']
    },
    BankName:{
        type:String,
        default:""
    },
    LoanAmount:{
        type:Number,
        default:0
    },
    NameofvaluationAgency:{
        type:String,
        default:""
    },
    DateofTechnicalInitiation:{
        type:Date
    },
    ApplicantsNames:{
        type:String,
        default:""
    },
    DateofSiteVisit:{
        type:Date
    },
    Requestform:{
        type:String,
        default:""
    },
    DateofReportrelease:{
        type:Date
    },
    ProposalIdApplicationNo:{
        type:String,
        default:""
    },
    TransactionType:{
        type:String,
        default:""
    },
    BranchnameID:{
        type:String,
        default:""
    },
    Requestfrom:{
        type:String,
        default:""
    },
    NameofCurrentOwnerSeller:{
        type:String,
        default:""
    },
    NameofthePersonmetAtasite:{
        type:String,
        default:""
    },
    ContactDetailsOfPersonmetAtsite:{
        type:String,
        default:""
    },
    AddressAsperTRF:{
        type:String,
        default:"AdressAspertrf"
    },
    adressasperLegalDocuments:{
        type:String,
        default:"AdressAsperLegalDocuments"
    },
    AddressasperActualAtsite:{
        type:String,
        default:"AdressAsperActualSite"
    },
    StatusHolding:{
        type:String,
        enum:["Lease Holding","Free Holding"],
        default:"Free Holding"
    },
    DeleveryAgency:{
        type:String,
        default:""
    },
    TypeofProperty:{
        type:String,
        enum:["Flate","Bungalow","Row House","Duplex","Shop","Godown","Office","Industrial","Plot"," Under-Construction"],
        required: false
    },
    NameoftheState:{
        type:String,
        default:""
    },
    MainLocality:{
        type:String,
        default:""
    },
    SubLocality:{
        type:String,
        default:""
    },
    StreetonwhichPropertyislocated:{
        type:String,
        default:""
    },
    NearestLandmark:{
        type:String,
        default:""
    },
    Pincode:{
        type:String,
        default:""
    },
    Occupationstatus:{
        type:String,
        enum:["Self","Seller", "Relative", "Vacant","Tenat","UnderConstruction"],
        default:"Self"
    },
    LocalityzoningtypeasperlatestDevelopmentMasterPlan:{
        type:String,
        enum:["Residential","Commercial","Industrial","Agriculture"],
        required: false
    },
    propertyUsage:{
        type:String,
        default:""
    },
    propertyidentified:{
        type:String,
        default:""
    },
    propertyDemarcatedSeperatly:{
        type:String,
        enum:['Yes','No'],
        default:"Yes"
    },
    propertyidentifiedThrough:{
        type:String,
        enum:['Person met at site'],
        default:"Person met at site"
    },
    NameoftheCityTownVillage:{
        type:String,
        default:""
    },
    RoofConstructionType:{
        type:String,
        enum:["RCC","Load Bearing","Steel Structure","Wooden","Other"],
        default:"RCC"
    },
    TypeofStructure:{
        type:String,
        enum:["Residential","Commercial","Industrial","Agricultural","Mixed Use","Other"],
        default:"Residential"
    },
    NumberofFloorsintheBuilding:{
        type:Number,
        default:1,
        min:0, 
        max:100
    },
    LocatedonfloorNo:{
        type:Number,
        default:1,
        min:0, 
        max:100
    },
    ExternalFinishing:{
        type:String,
        enum:["Good","Very Good","Average","Poor"],
        default:"Good"
    },
    InternalFinishing:{
        type:String,
        enum:["Good","Very Good","Average","Poor"],
        default:"Good"
    },    
    TypesofFlooring:{
        type:String,
        enum:["Vitrified Tiles","Ceramic Tiles","Marble","Granite","Wooden Flooring","Other"],
        default:"Vitrified Tiles"
    }, 
    PresentAgeofBuilding:{
        type:Number,
        default:0,
        min:0, 
        max:60
    },
    FuturePhysicalLifeofPropertyinyrs:{
        type:Number,
        default:0,
        min:0, 
        max:60
    },
    Latitude:{
        type:Number,
        default:0
    },
    Longitude:{
        type:Number,
        default:0
    },
    InfrastructureintheArea:{
        type:String,
        enum:["Good","Average","Poor"],
        default:"Good"
    },
    AmenitiesintheArea:{
        type:String,
        enum:["Good","Average","Poor"],
        default:"Good"
    },
    ClassofLocality:{
        type:String,
        enum:["High-end","Upper-Middle","Middle-end","Lower-end","Slum"],
        default:"Middle-end"
    },
    TypeOfRoad:{
        type:String,
        enum:["Tar","Concrete","WBM","Pandhan Road","Kutcha Road"],
        default:"Tar"
    },
    WidthOfRoad:{
        type:String,
        default:"5feet",
        enum:["5feet","10feet","15feet","20feet","25feet","30feet","35feet","40feet","45feet","50feet"]
    },
    ElectricficationElectricpole:{
        type:String,
        enum:['Yes','No'],
        default:"Yes"
    },
    DistanceFromBusStopKM:{
        type:Number,
        default:0
    },
    DistanceFromRailwayStationKM:{
        type:Number,
        default:0
    },
    DistanceFromMainMarketKM:{
        type:Number,
        default:0
    },
    PropertyfallsunderSeismicZone:{
        type:String,
        enum:["Zone II","Zone III","Zone IV","Zone V"],
        default:"Zone III"
    },
    PropertyfallsunderFloodZone:{
        type:String,
        enum:['Yes','No'],
        default:"No"
    },
    PropertyfallsunderCycloneZone:{
        type:String,
        enum:['Yes','No'],
        default:"No"
    },
    degreeriskofAssociation:{
        type:String,
        enum:["Low","Moderate","High"],
        default:"Moderate"
    },
    AnyriskofDemolition:{
        type:String,
        enum:['Low','Moderate','High'],
        default:"Moderate"
    },
    AsperDocumentsplanEastSiteBoundary:{
        type:String,
        default:""
    },
    AsperDocumentsplanWestSiteBoundary:{
        type:String,
        default:""
    },
    AsperDocumentsplanNorthSiteBoundary:{
        type:String,
        default:""
    },
    AsperDocumentsplanSouthSiteBoundary:{
        type:String,
        default:""
    },
    AsperActualSiteplanEastSiteBoundary:{
        type:String,
        default:""
    },
    AsperActualSiteplanWestSiteBoundary:{
        type:String,
        default:""
    },
    AsperActualSiteplanNorthSiteBoundary:{
        type:String,
        default:""
    },
    AsperActualSiteplanSouthSiteBoundary:{  
        type:String,
        default:""
    },
    BoundariesMatching:{
        type:String,
        enum:['Yes','No'],
        default:"Yes"
    },
    IfnothenReasonsforBoundariesnotMatching:{
        type:String,
        default:""
    },
    legalAreaAsperDocumentsEASTsite:{ 
        type:String,
        default:"0"
    },
    legalAreaAsperDocumentsWESTsite:{
        type:String,
        default:"0"
    },
    legalAreaAsperDocumentsNORTHsite:{
        type:String,
        default:"0"
    },
    legalAreaAsperDocumentsSOUTHsite:{
        type:String,
        default:"0"
    },
    TotalAreaAsperDocuments:{
        type:String,
        default:"0"
    },
    legalAreaAsperActualSiteEASTsite:{
        type:String,
        default:"0"
    },
    legalAreaAsperActualSiteWESTsite:{
        type:String,
        default:"0"
    },
    legalAreaAsperActualSiteNORTHsite:{
        type:String,
        default:"0"
    },
    legalAreaAsperActualSiteSOUTHsite:{
        type:String,
        default:"0"
    },
    TotalAreaAsperActualSite:{
        type:String,
        default:"0"
    },
    GroundFloorAccommodation:{
        type:String,
        enum:["Residential","Commercial","Industrial","Agricultural","Mixed Use","Other"],
        default:"Residential"
    },
    GroundFloorCarpetAreainSqftAspersanctionPlan:{
        type:String,
        default:"0"
    },
    GroundFloorCarpetAreainSqftAsperActualSiteMeasurements:{
        type:String,
        default:"0"
    },
    GroundFloorPermissiblePlanAreaInSqft:{
        type:String,
        default:"0"
    },
    GroundFloorAdoptedAreainSqft:{
        type:String,
        default:"0"
    },
    FirstFloorAccommodation:{
        type:String,
        enum:["Residential","Commercial","Industrial","Agricultural","Mixed Use","Other"],
        default:"Residential"
    },
    FirstFloorCarpetAreainSqftAspersanctionPlan:{
        type:String,
        default:"0"
    },
    FirstFloorCarpetAreainSqftAsperActualSiteMeasurements:{
        type:String,
        default:"0"
    },
    FirstFloorPermissiblePlanAreaInSqft:{
        type:String,
        default:"0"
    },
    FirstFloorAdoptedAreainSqft:{
        type:String,
        default:"0"
    },
    SecondFloorAccommodation:{
        type:String,
        enum:["Residential","Commercial","Industrial","Agricultural","Mixed Use","Other"],
        default:"Residential"
    },
    SecondFloorCarpetAreainSqftAspersanctionPlan:{
        type:String,
        default:"0"
    },
    SecondFloorCarpetAreainSqftAsperActualSiteMeasurements:{
        type:String,
        default:"0"
    },
    SecondFloorPermissiblePlanAreaInSqft:{
        type:String,
        default:"0"
    },
    SecondFloorAdoptedAreainSqft:{
        type:String,
        default:"0"
    },
    ThirdFloorAccommodation:{
        type:String,
        enum:["Residential","Commercial","Industrial","Agricultural","Mixed Use","Other"],
        default:"Residential"
    },
    ThirdFloorCarpetAreainSqftAspersanctionPlan:{
        type:String,
        default:"0"
    },
    ThirdFloorCarpetAreainSqftAsperActualSiteMeasurements:{
        type:String,
        default:"0"
    },
    ThirdFloorPermissiblePlanAreaInSqft:{
        type:String,
        default:"0"
    },
    ThirdFloorAdoptedAreainSqft:{
        type:String,
        default:"0"
    },
    ThirdFloorTotalCarpetAreainSqftAspersanctionPlan:{
        type:String,
        default:"0"
    },
    ThirdFloorTotalCarpetAreainSqftAsperActualSiteMeasurements:{
        type:String,
        default:"0"
    },
    ThirdFloorTotalPermissiblePlanAreaInSqft:{
        type:String,
        default:"0"
    },
    ThirdFloorTotalAdoptedAreainSqft:{
        type:String,
        default:"0"
    },
    FourthFloorAccommodation:{
        type:String,
        enum:["Residential","Commercial","Industrial","Agricultural","Mixed Use","Other"],
        default:"Residential"
    },
    FourthFloorCarpetAreainSqftAspersanctionPlan:{
        type:String,
        default:"0"
    },
    FourthFloorCarpetAreainSqftAsperActualSiteMeasurements:{
        type:String,
        default:"0"
    },
    FourthFloorPermissiblePlanAreaInSqft:{
        type:String,
        default:"0"
    },
    FourthFloorAdoptedAreainSqft:{
        type:String,
        default:"0"
    },
    FourthFloorTotalCarpetAreainSqftAspersanctionPlan:{
        type:String,
        default:"0"
    },
    FourthFloorTotalCarpetAreainSqftAsperActualSiteMeasurements:{
        type:String,
        default:"0"
    },
    FourthFloorTotalPermissiblePlanAreaInSqft:{
        type:String,
        default:"0"
    },
    FourthFloorTotalAdoptedAreainSqft:{
        type:String,
        default:"0"
    },
    TotalLoadingPercentageoncarpetAreaplusBalconeyplusdryBalcony:{
        type:String,
        default:"0"
    },
    TotalAreaWithLoadingSqft:{
        type:String,
        default:"0"
    },
    LayoutplanDetails:{
        type:String,
        default:""
    },
    BuildingSanctionApprovedPlanDetails:{
        type:String,
        default:""
    },
    completionCertificateOccupationCertificateNoBCC:{
        type:String,
        default:""
    },
    OtherDocuments:{
        type:String,
        default:""
    },
    OwnershipDocuments:{
        type:String,
        default:""
    },
    PropertyOwnerAsperDocuments:{
        type:String,
        default:""
    },
    isthePropertywithinMunicipalLimits:{
        type:String,
        enum:['Yes','No'],
        default:"Yes"
    },
    ifPlansnotAvailableWhetherinStructureConformingtotheLocalByelaws:{
        type:String,
        enum:['Yes','No'],
        default:"Yes"
    },
    LandPlotAreainSqft:{
        type:String,
        default:"0"
    },
    AdoptableBuiltUpAreaInSqft:{
        type:String,
        default:"0"
    },
    RateRangeofinthelocalityperSqft:{
        type:String,
        default:"0"
    },
    ConstructionCostperSqft:{
        type:String,
        default:"0"
    },
    RecommendedRateofLandperSqft:{
        type:String,
        default:"0"
    },
    TotalConstructionValueFor100PercentComplateBuildinginRS:{
        type:String,
        default:"0"
    },
    PlsspecifyifAnyspecialamenitiesProvided:{
        type:String,
        default:""
    },
    AdditionalCostIncurredForAmenitiesinRS:{
        type:String,
        default:"0"
    },
    TotalLandValueinRS:{
        type:String,
        default:"0"
    },
    TotalConstructionValueAtpresentConstructionStageinRS:{
        type:String,
        default:"0"
    },
    TotalFairMarketValueAt100PercentCompletioninRS:{
        type:String,
        default:"0"
    },
    TotalFairMarketValueonpresentcompletionstageinRS:{
        type:String,
        default:"0"
    },
    TotalRealizableValueAt100PercentCompletioninRS:{
        type:String,
        default:"0"
    },
    TotalRealizableValueonpresentcompletionstageinRS:{
        type:String,
        default:"0"
    },
    TotalForcedDistresedValueAt100PercentCompletioninRS:{
        type:String,
        default:"0"
    },
    TotalForcedDistresedValueonpresentcompletionstageinRS:{
        type:String,
        default:"0"
    },
    SBUAsquretFeet:{
        type:String,
        default:"0"
    },
    AdoptedRateinsqureFeet:{
        type:String,
        default:"0"
    },
    TotalValueofflateShopFlateOfficeon100PercentCompletinRS:{
        type:String,
        default:"0"
    },
    AddionalCostIncurredforAmenitiesinRS:{
        type:String,
        default:"0"
    },
    TotalFairMarketValueAt100PercentCompletioninRS:{
        type:String,
        default:"0"
    },
    TotalFairMarketValueonpresentcompletionstageinRS:{
        type:String,
        default:"0"
    },
    TotalRealizableValueAt100PercentCompletioninRS:{
        type:String,
        default:"0"
    },
    TotalRealizableValueonpresentcompletionstageinRS:{
        type:String,
        default:"0"
    },
    TotalForcedDistresedValueAt100PercentCompletioninRS:{
        type:String,
        default:"0"
    },
    TotalForcedDistresedValueonpresentcompletionstageinRS:{
        type:String,
        default:"0"
    },
    TotalForcedDistressedValueat100PercentCompletioninRS:{
        type:String,
        default:"0"
    },
    TotalForcedDistressedValueonpresentcompletionstageinRS:{
        type:String,
        default:"0"
    },
    persentageCompletionofConstruction:{
        type:String,
        default:"0"
    },
    percentageRecommendation:{
        type:String,
        default:"0"
    },
    GovermentGuidelinesCirclerateforLandRsperSqft:{
        type:String,
        default:"0"
    },
    LandValueAsperGovermentRateRsperSqft:{
        type:String,
        default:"0"
    },
    GovernmentGuidelinesCirclerateforFlatUnitBuiltUpRsperSqft:{
        type:String,
        default:"0"
    },
    FlatUnitBuiltUpValueAsperGovermentRateRsperSqft:{
        type:String,
        default:"0"
    },
    ForcedSaleVAlueInRSperSqft:{
        type:String,
        default:"0"
    },
    AvgRentalpersqftinRS:{
        type:String,
        default:"0"
    },
    RealizableValueinRS:{
        type:String,
        default:"0"
    },
    Remark1:{
        type:String,
        default:""
    },
    Remark2:{   
        type:String,
        default:""
    },
    Remark3:{
        type:String,
        default:""
    },
    Remark4:{
        type:String,
        default:""
    },
    Remark5:{
        type:String,
        default:""
    },
    Declaration:{
        type:String,
        default:""
    },
    desclaimer:{
        type:String,
        default:""
    },
    Uploadphotosatelitemap:{
        type:String,
        default:""
    },
    UploadphotoHall:{
        type:String,
        default:""
    },
    UploadphotoKichen:{
        type:String,
        default:""
    },
    UploadphotoBedroom:{
        type:String,
        default:""
    },
    UploadphotoOtherroom:{
        type:String,
        default:""
    },
    UploadphotoOther:{
        type:String,
        default:""
    },
    UploadphotoExternalPhoto:{
        type:String,
        default:""
    },
    UploadphotoFrontSIte:{
        type:String,
        default:""
    },
    UploadphotoRoadSIte:{
        type:String,
        default:""
    },
    UploadphotoSelfiWithProperty:{
        type:String,
        default:""
    },
    UploadphotoSelfiWithpersonAtProperty:{
        type:String,
        default:""
    },
    images:{
        type:[String],
        default:[]
    },
    assignedTo:{
        type:String,
        enum:["office-engineer","site-engineer","technical-engineer","valuer","sales-team"],
        default:"office-engineer"
    },
    status:{
        type:String,
        enum:["draft","submitted","in-review","completed"],
        default:"draft"
    },
    workflowStage:{
        type:String,
        enum:["office-engineer","site-engineer","office-engineer-review","valuer","completed"],
        default:"office-engineer"
    },
    isUpdated:{
        type:Boolean,
        default:false
    },
    updatedBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        default:null
    },
    finalReportId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'AusmallFinanceFinalReport',
        default:null
    }
},{timestamps:true});

const ausmallFinanceFormModel = mongoose.model('AusmallFinanceForm', ausmallFinanceFormSchema);
export default ausmallFinanceFormModel;


